// localHost Deploy

###
GET http://localhost:3000/contacts

###
GET http://localhost:3000/contacts/62643d312cb029dd5b2a2214

### Create Contact
POST http://localhost:3000/contacts/ HTTP/1.1
content-type: application/json

{
    "firstName": "Michael",
    "lastName": "Smith",
    "email": "michaelSmith@gmail.com",
    "favoriteColor": "blue",
    "birthday": "10/10/1990"
}

### Update contact. Use whatever field you want, or all of them.
PUT http://localhost:3000/contacts/62643d312cb029dd5b2a2214 HTTP/1.1
content-type: application/json

{
    "firstName": "Jason"
}

### Delete contact
DELETE http://localhost:3000/contacts/6267358e071fa3ef007b74cd HTTP/1.1


// PRODUCTION Deploy

###
GET https://nodejs-cse341.herokuapp.com/contacts

###
GET https://nodejs-cse341.herokuapp.com/contacts/6267387954d962f09253b3f0

### Create Contact
POST https://nodejs-cse341.herokuapp.com/contacts/ HTTP/1.1
content-type: application/json

{
    "firstName": "Michael",
    "lastName": "Smith",
    "email": "michaelSmith@gmail.com",
    "favoriteColor": "blue",
    "birthday": "10/10/1990"
}

### Update contact. Use whatever field you want, or all of them.
PUT https://nodejs-cse341.herokuapp.com/contacts/62643d312cb029dd5b2a2214 HTTP/1.1
content-type: application/json

{
    "firstName": "Joaquin"
}

### Delete contact
DELETE https://nodejs-cse341.herokuapp.com/contacts/6267387954d962f09253b3f0 HTTP/1.1

